const DISTRICTS = [
  'Kathmandu',
  'Lalitpur',
  'Bhaktapur',
  'Kavrepalanchok',
  'Sindhupalchok',
  'Makwanpur',
  'Chitwan',
  'Nawalpur',
  'Kaski',
  'Lamjung',
  'Syangja',
  'Parbat',
  'Baglung',
  'Myagdi',
  'Gorkha',
  'Tanahun',
  'Dhading',
  'Rasuwa',
  'Nuwakot',
  'Dolakha',
  'Ramechhap',
  'Okhaldhunga',
  'Solukhumbu',
  'Sindhuli',
  'Udayapur',
  'Sarlahi',
  'Mahottari',
  'Dhanusha',
  'Siraha',
  'Saptari',
  'Morang',
  'Sunsari',
  'Jhapa',
  'Ilam',
  'Panchthar',
  'Taplejung',
  'Sankhuwasabha',
  'Bhojpur',
  'Terhathum',
  'Dhankuta',
  'Khotang',
  'Rupandehi',
  'Kapilvastu',
  'Nawalparasi',
  'Dang',
  'Banke',
  'Bardiya',
  'Pyuthan',
  'Rolpa',
  'Rukum',
  'Arghakhanchi',
  'Gulmi',
  'Palpa',
  'Dailekh',
  'Surkhet',
  'Jajarkot',
  'Salyan',
  'Rukum West',
  'Kailali',
  'Kanchanpur',
  'Dadeldhura',
  'Doti',
  'Achham',
  'Bajhang',
  'Bajura',
  'Baitadi',
  'Darchula',
  'Dolpa',
  'Humla',
  'Jumla',
  'Kalikot',
  'Mugu',
  'Mustang',
  'Manang',
  'Rukum East',
];

const normalize = (value = '') => value.toLowerCase().replace(/\s+/g, ' ').trim();

const extractDistrict = (text = '') => {
  const normalized = normalize(text);
  const matched = DISTRICTS.find((district) => normalized.includes(normalize(district)));

  return matched || 'Unknown';
};

module.exports = {
  DISTRICTS,
  extractDistrict,
  normalize,
};
